version: '3.9'

services:
  SincronizarProtocoloEFundacao:
    image: sincronizarprotocoloefundacao
    hostname: SincronizarProtocoloEFundacao
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - NODE_ENV=production
      - TOPIC=SincronizarProtocoloEFundacaoTask
      - ENG_REST_URL=${CAMUNDA_URL}
      - ENG_REST_USERNAME=${CAMUNDA_USERNAME}
      - ENG_REST_PASSWORD=${CAMUNDA_PASSWORD}
      - MAX_TASK_DURATION=30000
      - PROTO_USER_DB=${PROTO_USER_DB}
      - PROTO_PASSWD_DB=${PROTO_PASSWD_DB}
      - PROTO_HOST_DB=${PROTO_HOST_DB}
      - PROTO_PORT_DB=${PROTO_PORT_DB}
      - PROTO_DB=${PROTO_DB}
      - RTVE_HOST=${RTVE_HOST}
      - RTVE_USER=${RTVE_USER}
      - RTVE_PASSWD=${RTVE_PASSWD}
      - RTVE_COVENANT=${RTVE_COVENANT}
      - DEV_SSH_HOST_NAME=${DEV_SSH_HOST_NAME}
      - DEV_SSH_HOST_USER=${DEV_SSH_HOST_USER}
      - DEV_SSH_HOST_PASS=${DEV_SSH_HOST_PASS}
      - SITES_SSH_HOST_NAME=${SITES_SSH_HOST_NAME}
      - SITES_SSH_HOST_USER=${SITES_SSH_HOST_USER}
      - SITES_SSH_HOST_PASS=${SITES_SSH_HOST_PASS}
      - SIGA-SER_SSH_HOST_NAME=${SIGA-SER_SSH_HOST_NAME}
      - SIGA-SER_SSH_HOST_USER=${SIGA-SER_SSH_HOST_USER}
      - SIGA-SER_SSH_HOST_PASS=${SIGA-SER_SSH_HOST_PASS}

networks:
  default:
    name: backend
    external: true